// Code generated by entc, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"github.com/facebook/ent/dialect/sql"
	"github.com/goops-top/ent-pro/ent/owner"
)

// Owner is the model entity for the Owner schema.
type Owner struct {
	config
	// ID of the ent.
	ID int `json:"id,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Owner) scanValues() []interface{} {
	return []interface{}{
		&sql.NullInt64{}, // id
	}
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Owner fields.
func (o *Owner) assignValues(values ...interface{}) error {
	if m, n := len(values), len(owner.Columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	value, ok := values[0].(*sql.NullInt64)
	if !ok {
		return fmt.Errorf("unexpected type %T for field id", value)
	}
	o.ID = int(value.Int64)
	values = values[1:]
	return nil
}

// Update returns a builder for updating this Owner.
// Note that, you need to call Owner.Unwrap() before calling this method, if this Owner
// was returned from a transaction, and the transaction was committed or rolled back.
func (o *Owner) Update() *OwnerUpdateOne {
	return (&OwnerClient{config: o.config}).UpdateOne(o)
}

// Unwrap unwraps the entity that was returned from a transaction after it was closed,
// so that all next queries will be executed through the driver which created the transaction.
func (o *Owner) Unwrap() *Owner {
	tx, ok := o.config.driver.(*txDriver)
	if !ok {
		panic("ent: Owner is not a transactional entity")
	}
	o.config.driver = tx.drv
	return o
}

// String implements the fmt.Stringer.
func (o *Owner) String() string {
	var builder strings.Builder
	builder.WriteString("Owner(")
	builder.WriteString(fmt.Sprintf("id=%v", o.ID))
	builder.WriteByte(')')
	return builder.String()
}

// Owners is a parsable slice of Owner.
type Owners []*Owner

func (o Owners) config(cfg config) {
	for _i := range o {
		o[_i].config = cfg
	}
}
